title: Hamish Browne Resume
description:  A web resume for engineering co-op student HOBB
url: https://hobb.info
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
